# Generated by Django 3.0.4 on 2020-04-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200418_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
